In [69]:
# ¿Qué es NumPy?
# Numpy se utiliza para trabajar con múltiples dimensiones. (array de objetos multidimensionales)

In [3]:
# PRIMER PASO: importar la librería de Numpy
import numpy as np

In [8]:
# Podemos calcular su versión
np.__version__ # El profe tiene 1.21.5

'1.26.4'

In [7]:
# Vamos a crear un array con NumPy
lista = np.array([1,2,3,4])
print(lista)

[1 2 3 4]


In [17]:
# Cómo podemos saber el id interno de una variable?
print(f"lista1: {id(lista)}")
# Si tengo dos variables que tienen el mismo identificador es porque son la misma, tienen la misma referencia en memoria

lista1: 1852348185840


In [19]:
# Podemos hacer copias de las listas
print(f"lista1: {id(lista)}")
lista2 = np.copy(lista)
print("lista2:", id(lista2))

lista1: 1852348185840
lista2: 1852348405424


In [21]:
# Podemos hacer objetos
objeto = np.array({"pizza": 10, "manzana": 3, "galletas": 2})

print(objeto, type(objeto))

{'pizza': 10, 'manzana': 3, 'galletas': 2} <class 'numpy.ndarray'>


In [22]:
# Podemos crear un array de un set
arraySinRepetidos = np.array({1,1,2,3,2,3,1,2})
print(arraySinRepetidos)

{1, 2, 3}


In [41]:
# Tenemos la función arange que me crea un array de datos en vez de una lista de datos que es lo que hacía el range.
# Pero ¡ojo! mira lo siguiente:

array = [i for i in np.arange(10)]
array2 = np.arange(10)

print(array, f"tamaño: {len(array)}") # -> LISTA
print(array2, f"tamaño: {array2.size}") # -> ARRAY

# ¡Recuerda! Todas las operaciones que se hagan con los arrays de NumPy serán mucho más eficientes que las listas de Python

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] tamaño: 10
[0 1 2 3 4 5 6 7 8 9] tamaño: 10


In [40]:
array3 = np.array([111, 2.3, True, False, "test"])
array4 = np.array([111, 2.3, True, False])

# NumPy convierte todos los elementos a string porque es el tipo que puede contener todos los demás tipos sin pérdida de información.
# Esto se conoce como "upcasting". Entonces, todos los elementos en array3 se convierten en cadenas de texto.
print(f"Array 3: {array3}", end="\n\n")
print(f"Tipo elem 0: {type(array3[0])}")
print(f"Tipo elem 1: {type(array3[1])}")
print(f"Tipo elem 2: {type(array3[2])}")
print(f"Tipo elem 2: {type(array3[3])}")
print(f"Tipo elem 2: {type(array3[4])} ",end="\n\n")

# En este caso por ejemplo los convierte en float

print(f"Array 4: {array4}", end="\n\n")
print(f"Tipo elem 0: {type(array4[0])}")
print(f"Tipo elem 1: {type(array4[1])}")
print(f"Tipo elem 2: {type(array4[2])}")
print(f"Tipo elem 2: {type(array4[3])}")



Array 3: ['111' '2.3' 'True' 'False' 'test']

Tipo elem 0: <class 'numpy.str_'>
Tipo elem 1: <class 'numpy.str_'>
Tipo elem 2: <class 'numpy.str_'>
Tipo elem 2: <class 'numpy.str_'>
Tipo elem 2: <class 'numpy.str_'> 

Array 4: [111.    2.3   1.    0. ]

Tipo elem 0: <class 'numpy.float64'>
Tipo elem 1: <class 'numpy.float64'>
Tipo elem 2: <class 'numpy.float64'>
Tipo elem 2: <class 'numpy.float64'>


In [43]:
# Creación de un espacio lineal: np.linspace(inicio, fin, num)

# Esto crea una secuencia de 5 números, distribuidos de manera equidistante entre 1 y 10 (incluyendo ambos extremos) 
print(np.linspace(1,10,5))


[ 1.    3.25  5.5   7.75 10.  ]


In [68]:
# Creación de array de 1: np.ones(tamaños)
print(np.ones(10), end="\n\n")

# Creación de una dimensión de 1s de 2x3
print(np.ones((2,3)), end="\n\n")

# Creación de array de 0: np.zeros(tamaño)
print(np.zeros(10), end="\n\n")

# Creación de una dimensión de 0s de 2x3
print(np.zeros((2,3), dtype="int32"), end="\n\n") #-> le podemos especificar el dtype 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0 0 0]
 [0 0 0]]



In [125]:
# Saber más sobre los dtype

# uint8: valores entre 0 y 255
# floa32: representa valores con decimales
# float64: número con coma flotante de 64 bits

z = np.array(3, dtype="uint8")
print(z)

z1 = np.array([1,2,3], dtype='d')
print(z1)

3
[1. 2. 3.]


In [72]:
# Creación de matrices en Numpy
matriz = [[1,2,3], [4,5,6]]
matriz_unidimensional = [1,2,3]

matrizNumpy= np.array(matriz)
matrizNumpyUnidimensional = np.array(matriz_unidimensional)
print(matrizNumpy)

# Información sobre la matriz:
print(f"Las dimensiones de la matriz son: {matrizNumpy.ndim}")
print(f"El tamaño de la matriz es de {matrizNumpy.shape}, es decir, 2 filas 3 columnas")
print(f"El data type de la matriz es: {matrizNumpy.dtype}")

print()
# Información sobre la matriz unidimensional:
print(f"Las dimensiones de la matriz son: {matrizNumpyUnidimensional.ndim}")
print(f"El tamaño de la matriz es de {matrizNumpyUnidimensional.shape}, es decir, 3 elementos")
print(f"El data type de la matriz es: {matrizNumpyUnidimensional.dtype}")


[[1 2 3]
 [4 5 6]]
Las dimensiones de la matriz son: 2
El tamaño de la matriz es de (2, 3), es decir, 2 filas 3 columnas
El data type de la matriz es: int32

Las dimensiones de la matriz son: 1
El tamaño de la matriz es de (3,), es decir, 3 elementos
El data type de la matriz es: int32


In [124]:
# Las matrices de NumPy se pueden redimensionar:
array5 = np.arange(15)
print(array5)
print()

print("Redimensionamos en 3 filas 5 columnas:")
array5 = array5.reshape((3,5))
print(array5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Redimensionamos en 3 filas 5 columnas:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# Si quiero obtener una matriz de 2x3 con valores random
matriz_random = np.random.random((2,3))
print(matriz_random)

In [86]:
# Calcular la media de un array
array6 = np.arange(15)
print(f"La media del array: {array6} es: {np.mean(array6)}")

La media del array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] es: 7.0


In [88]:
%%time
# Calcular el tiempo que tarda una función
suma = 0
for i in range(1000000):
    suma += i

CPU times: total: 266 ms
Wall time: 342 ms


In [98]:
# Append de arrays
a2d = np.array([[1,2],[3,4]])
print(a2d, end="\n\n")

b2d = np.append(a2d,[[9,9]], axis = 0)
#c2d = np.append(a2d,[[9,9]], axis = 1)

print(b2d, end="\n\n")
#print(c2d, end="\n\n")

[[1 2]
 [3 4]]

[[1 2]
 [3 4]
 [9 9]]



In [101]:
# ¿Que es el axis?
# Cuando se especifica el valor de axis, defines en qué dimensión se agregarán los valores.

a = np.array([[1, 2, 3], [4, 5, 6]])
result = np.append(a, [[7, 8, 9]], axis=0)
print(result)

print()

a = np.array([[1, 2, 3], [4, 5, 6]])
result = np.append(a, [[7], [8]], axis=1)
print(result)

# Resumen:
# axis=None: Aplana el array y añade los valores al final.
# axis=0: Agrega filas (los valores que agregues deben tener el mismo número de columnas).
# axis=1: Agrega columnas (los valores que agregues deben tener el mismo número de filas).


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3 7]
 [4 5 6 8]]


In [104]:
import numpy as np

# Crear arrays de ejemplo
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# En NumPy, el operador suma realiza la suma elemento a elemento
suma = a + b
print(f"Suma de arrays: {suma}")  # Resultado: [5 7 9]

# El operador de resta
resta = a - b
print(f"Resta de arrays: {resta}")  # Resultado: [-3 -3 -3]

# El operador de división
division = a / b
print(f"División de arrays: {division}")  # Resultado: [0.25 0.4  0.5]

# El operador de multiplicación
multiplicacion = a * b
print(f"Multiplicación de arrays: {multiplicacion}")  # Resultado: [4 10 18]

# Multiplicar una lista de NumPy por un escalar
escalar = 10
multiplicacion_escalar = a * escalar
print(f"Multiplicación por un escalar: {multiplicacion_escalar}")  # Resultado: [10 20 30]

# Concatenar arrays
concatenado = np.concatenate((a, b))
print(f"Concatenación: {concatenado}")


Suma de arrays: [5 7 9]
Resta de arrays: [-3 -3 -3]
División de arrays: [0.25 0.4  0.5 ]
Multiplicación de arrays: [ 4 10 18]
Multiplicación por un escalar: [10 20 30]
Concatenación: [1 2 3 4 5 6]


In [108]:
# Función tile: 

# Repetir un array unidimensional
a = np.array([1, 2, 3])
resultado = np.tile(a, 2)
print(resultado)
# En este ejemplo, el array [1, 2, 3] se repite 2 veces de manera horizontal, formando un nuevo array unidimensional.

print("")

# Repetir un array en múltiples dimensiones:
a = np.array([[1, 2], [3, 4]])
resultado = np.tile(a, (2, 3))
print(resultado)

# Aquí, el array original a se repite 2 veces a lo largo del eje 0 (filas) y 3 veces a lo largo del eje 1 (columnas). 
# El parámetro (2, 3) indica cuántas veces se repite en cada dimensión.


[1 2 3 1 2 3]

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [109]:
# Operaciones de comparación

# Arrays de ejemplo
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

# Comparaciones entre arrays
igualdad = a == b          # [False, False, False, False]
desigualdad = a != b       # [True, True, True, True]
mayor_que = a > b          # [False, False, True, True]
menor_que = a < b          # [True, True, False, False]
mayor_o_igual = a >= b     # [False, False, True, True]
menor_o_igual = a <= b     # [True, True, False, False]

# Comparación con un escalar
mayor_que_2 = a > 2        # [False, False, True, True]

# Verificar si todas o alguna de las comparaciones son verdaderas
todos_mayores_que_0 = np.all(a > 0)  # True
alguno_mayor_que_3 = np.any(a > 3)   # True

# Imprimir resultados
print("Igualdad:", igualdad)
print("Desigualdad:", desigualdad)
print("Mayor que:", mayor_que)
print("Menor que:", menor_que)
print("Mayor o igual:", mayor_o_igual)
print("Menor o igual:", menor_o_igual)
print("Mayor que 2:", mayor_que_2)
print("Todos mayores que 0:", todos_mayores_que_0)
print("Alguno mayor que 3:", alguno_mayor_que_3)


Igualdad: [False False False False]
Desigualdad: [ True  True  True  True]
Mayor que: [False False  True  True]
Menor que: [ True  True False False]
Mayor o igual: [False False  True  True]
Menor o igual: [ True  True False False]
Mayor que 2: [False False  True  True]
Todos mayores que 0: True
Alguno mayor que 3: True


In [110]:
# Más operaciones

import numpy as np

# Array de ejemplo
a = np.array([1, 2, 3, 4])

# Operaciones
suma_acumulativa = np.cumsum(a)        # Suma acumulativa
producto_acumulativo = np.cumprod(a)   # Producto acumulativo
varianza = np.var(a)                   # Varianza
desviacion_estandar = np.std(a)        # Desviación estándar
suma_total = np.sum(a)                 # Suma total
producto_total = np.prod(a)            # Producto total
minimo = np.min(a)                     # Mínimo
maximo = np.max(a)                     # Máximo
media = np.mean(a)                     # Media (promedio)
mediana = np.median(a)                 # Mediana
percentil_50 = np.percentile(a, 50)    # Percentil 50 (Mediana)

# Imprimir resultados
print(f"Suma acumulativa: {suma_acumulativa}")
print(f"Producto acumulativo: {producto_acumulativo}")
print(f"Varianza: {varianza}")
print(f"Desviación estándar: {desviacion_estandar}")
print(f"Suma total: {suma_total}")
print(f"Producto total: {producto_total}")
print(f"Mínimo: {minimo}")
print(f"Máximo: {maximo}")
print(f"Media: {media}")
print(f"Mediana: {mediana}")
print(f"Percentil 50: {percentil_50}")


Suma acumulativa: [ 1  3  6 10]
Producto acumulativo: [ 1  2  6 24]
Varianza: 1.25
Desviación estándar: 1.118033988749895
Suma total: 10
Producto total: 24
Mínimo: 1
Máximo: 4
Media: 2.5
Mediana: 2.5
Percentil 50: 2.5


In [111]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Media de todos los elementos
media_total = np.mean(a)
print("Media total:", media_total)

# Media por columnas (axis=0)
media_columnas = np.mean(a, axis=0)
print("Media por columnas:", media_columnas)

# Media por filas (axis=1)
media_filas = np.mean(a, axis=1)
print("Media por filas:", media_filas)


Media total: 5.0
Media por columnas: [4. 5. 6.]
Media por filas: [2. 5. 8.]


In [114]:
# Generación de números aleatorios con/sin semilla

# Establece una "semilla" para el generador, lo que asegura que los números aleatorios generados sean reproducibles. 
# En otras palabras, usando la misma semilla, obtendrás la misma secuencia de números aleatorios cada vez que ejecutes el código.

# Con semilla
np.random.seed(123)
print("Con semilla 123:", np.random.rand(3))

# Sin semilla
print("Sin semilla 1:", np.random.rand(3))
print("Sin semilla 2:", np.random.rand(3))

# Volver a establecer la misma semilla
np.random.seed(123)
print("Con semilla 123 (repetido):", np.random.rand(3))

Con semilla 123: [0.69646919 0.28613933 0.22685145]
Sin semilla 1: [0.55131477 0.71946897 0.42310646]
Sin semilla 2: [0.9807642  0.68482974 0.4809319 ]
Con semilla 123 (repetido): [0.69646919 0.28613933 0.22685145]


In [115]:
# Generar un número entero aleatorio entre 1 y 10 (inclusive de 1, exclusivo de 10)
numero = np.random.randint(1, 10)
print(numero)  # Resultado puede ser: 3

7


In [116]:
# Producto matricial:

# Definir dos matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Producto matricial usando @
producto_matricial = A @ B
print("Producto matricial usando @:")
print(producto_matricial)
print()

# Producto matricial usando .dot()
producto_matricial_dot = A.dot(B)
print("Producto matricial usando .dot():")
print(producto_matricial_dot)

Producto matricial usando @:
[[19 22]
 [43 50]]

Producto matricial usando .dot():
[[19 22]
 [43 50]]


In [120]:
# Matriz traspuesta
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Matriz traspuesta usando .T
A_traspuesta = A.T
print("Matriz traspuesta usando .T:")
print(A_traspuesta)
print()

# Matriz traspuesta usando np.transpose() --> La transpuesta intercambia sus filas por columnas
A_traspuesta_np = np.transpose(A)
print("Matriz traspuesta usando np.transpose():")
print(A_traspuesta_np)

Matriz traspuesta usando .T:
[[1 4]
 [2 5]
 [3 6]]

Matriz traspuesta usando np.transpose():
[[1 4]
 [2 5]
 [3 6]]


In [135]:
B = np.array([[1, 2],
              [3, 4]])

# Calcular el determinante de una matriz (multiplicar todas las diagonales de arriba a abajo e ir sumandolas y
# restar las diagonales de abajo a arriba)
# determinante = np.linalg.det(A)
# print(f"Determinante de B: {determinante}")


# Calcular la inversa de la matriz usando np.linalg.inv()
B_inversa = np.linalg.inv(B)
print("Inversa de la matriz B:")
print(B_inversa)
print()

# Verificar el resultado
# Multiplicación de la matriz original por su inversa debe dar la matriz identidad
producto_identidad = B @ B_inversa
print("Producto de B por su inversa (debería ser la identidad):")
print(producto_identidad)

Inversa de la matriz B:
[[-2.   1. ]
 [ 1.5 -0.5]]

Producto de B por su inversa (debería ser la identidad):
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [127]:
# Máscaras booleanas
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Crear una máscara booleana para seleccionar elementos mayores que 5
mask = arr > 5

# Aplicar la máscara al array
filtered_arr = arr[mask]

print("Máscara booleana:", mask)
print("Array filtrado:", filtered_arr)



Máscara booleana: [False False False False False  True  True  True  True  True]
Array filtrado: [ 6  7  8  9 10]


In [128]:
# Máscara con valores específicos
arr = np.array([1, 2, 3, 4, 5, 3, 6, 7, 5])

# Crear una máscara para seleccionar elementos que sean 3 o 5
mask = (arr == 3) | (arr == 5)

# Aplicar la máscara al array
filtered_arr = arr[mask]

print("Máscara booleana:", mask)
print("Array filtrado:", filtered_arr)

Máscara booleana: [False False  True False  True  True False False  True]
Array filtrado: [3 5 3 5]


In [129]:
# Máscara con where:

r = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Obtener índices de elementos mayores que 5
indices = np.where(arr > 5)

# Filtrar el array usando los índices
filtered_arr = arr[indices]

print("Índices de los elementos filtrados:", indices)
print("Array filtrado:", filtered_arr)

Índices de los elementos filtrados: (array([6, 7], dtype=int64),)
Array filtrado: [6 7]


In [132]:
# Slice
import numpy as np

# Crear un array unidimensional
arr1d = np.array([10, 20, 30, 40, 50, 60, 70])

# Slicing simple
slice1 = arr1d[2:5]  # Selecciona elementos del índice 2 al 4
# Slicing con paso
slice2 = arr1d[::3]  # Selecciona cada tercer elemento
# Slicing con índices negativos
slice3 = arr1d[-5:-2]  # Selecciona los elementos desde el índice -5 hasta -3

print("Array unidimensional original:", arr1d)
print("Slicing simple:", slice1)
print("Slicing con paso:", slice2)
print("Slicing con índices negativos:", slice3)

# Crear un array bidimensional
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Slicing en arrays bidimensionales
slice2d_1 = arr2d[1:, 1:]  # Selecciona un subarray desde la fila 1 y columna 1 en adelante
# Slicing con paso en arrays bidimensionales
slice2d_2 = arr2d[::2, ::2]  # Selecciona cada segunda fila y cada segunda columna

print("\nArray bidimensional original:\n", arr2d, end="\n\n")
print("Slicing en 2D (desde fila 1 y columna 1):\n", slice2d_1, end="\n\n")
print("Slicing con paso en 2D:\n", slice2d_2, end="\n\n")


Array unidimensional original: [10 20 30 40 50 60 70]
Slicing simple: [30 40 50]
Slicing con paso: [10 40 70]
Slicing con índices negativos: [30 40 50]

Array bidimensional original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Slicing en 2D (desde fila 1 y columna 1):
 [[ 6  7  8]
 [10 11 12]]

Slicing con paso en 2D:
 [[ 1  3]
 [ 9 11]]



In [143]:
# Cosas curiosas

#1
array= np.array([10,20,30,40,50,60,70])
indexs = [2,3,4]

print(array[indexs])
print("--------")

#2
arr1d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr1d == arr2d)
print("--------")
print(arr1d is arr2d)
print("--------")

#3
print(arr1d.T)

[30 40 50]
--------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
--------
False
--------
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
