In [ ]:
### Practica

In [10]:
import numpy as np

prices = np.array([100,200,300])
discounts = np.array([0.9])

# Quiero aplicar este descuento a cada uno de los elementos
print(f"Precios con descuento: {np.array(prices*discounts, dtype=int)}")

Precios con descuento: [ 90 180 270]


In [15]:
# Crea un array de numpy de elementos de 100 a 500 que sea de 3x3
prices= np.array(np.random.randint(100,500, size=(3,3)))
discounst = np.array([10,20,30])

print(f"Precios con descuento:\n {prices-discounts}")

Precios con descuento:
 [[467.1 389.1 171.1]
 [404.1 463.1 172.1]
 [382.1 309.1 318.1]]


In [19]:
array = np.array([1,2,3,4,5])
print(np.all(array > 3))
print(np.any(array > 3))

False
True


In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])

concatenado = np.concatenate([a,b])

print(concatenado)
print(np.vstack([a,b]))
print(np.hstack([a,b]))



[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [35]:
c = np.arange(1,10)
split_c = np.split(c,3)
split_c


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [47]:
enc = ["bueno", "excelente", "malo", "bueno", "malo", "excelente", "bueno", "bueno", "malo", "excelente"]

# Valores únicos del array
print(np.array(set(enc)))
print(np.unique(enc))

# ¿Cuantas veces aparecen en el conjunto?
unique_elem, count = np.unique(enc, return_counts=True, )
print(unique_elem, count)
print(dict(zip(unique_elem, count)))

# Las copias se pueden hacer array[[1,2]]

{'malo', 'bueno', 'excelente'}
['bueno' 'excelente' 'malo']
['bueno' 'excelente' 'malo'] [4 3 3]
{'bueno': 4, 'excelente': 3, 'malo': 3}


In [66]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
print(a.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [69]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
# Hacer el reverse
np.arange(1,10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [75]:
np.arange(1,10).reshape(3,3).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])