In [3]:
!pip install tensorflow

     ---------------------------------------- 0.0/48.7 kB ? eta -:--:--
     ---------------------------------------- 48.7/48.7 kB ? eta 0:00:00
   ---------------------------------------- 0.0/390.2 MB ? eta -:--:--
   ---------------------------------------- 1.6/390.2 MB 50.6 MB/s eta 0:00:08
   ---------------------------------------- 4.5/390.2 MB 58.0 MB/s eta 0:00:07
    --------------------------------------- 7.1/390.2 MB 56.5 MB/s eta 0:00:07
    --------------------------------------- 9.4/390.2 MB 54.6 MB/s eta 0:00:07
   - -------------------------------------- 11.5/390.2 MB 54.7 MB/s eta 0:00:07
   - -------------------------------------- 14.0/390.2 MB 50.4 MB/s eta 0:00:08
   - -------------------------------------- 16.4/390.2 MB 50.4 MB/s eta 0:00:08
   - -------------------------------------- 19.0/390.2 MB 50.4 MB/s eta 0:00:08
   -- ------------------------------------- 21.6/390.2 MB 54.4 MB/s eta 0:00:07
   -- ------------------------------------- 23.7/390.2 MB 50.4 MB/s 

## Coding Exercise #0601

### 1. TensorFlow basics:

In [7]:
import tensorflow as tf
import numpy as np
import random

#### 1.1. Hello World!

In [9]:
hello = tf.constant("Hello World!")
tf.print(hello)

Hello World!


#### 1.2. Creating tensors:

In [11]:
hello = tf.constant("Hello World!")                         # String.
const_scalar = tf.constant(7)                               # A scalar tensor.
const_matrix = tf.constant([[1,2], [3,4]])                  # A matrix tensor.
mat_fill = tf.fill((4,4),9)                                 # A 4x4 tensor filled with 9s.
mat_zeros = tf.zeros((3,3))                                 # A 3x3 tensor filled with 0s.
mat_ones = tf.ones((5,5))                                   # A 5x5 tensor filled with 1s.
mat_randn = tf.random.normal((3,3), mean=0, stddev=1.0)     # 3x3 random normal tensor.
mat_randu = tf.random.uniform((4,4), minval=0, maxval=1.0)  # 4x4 random uniform tensor.

In [13]:
my_ops=[hello, const_scalar, const_matrix, mat_fill, mat_zeros, mat_ones, mat_randn, mat_randu]

for op in my_ops:
    tf.print(type(op))
    tf.print('\n')
    tf.print(op)
    tf.print('\n')

<class 'tensorflow.python.framework.ops.EagerTensor'>


Hello World!


<class 'tensorflow.python.framework.ops.EagerTensor'>


7


<class 'tensorflow.python.framework.ops.EagerTensor'>


[[1 2]
 [3 4]]


<class 'tensorflow.python.framework.ops.EagerTensor'>


[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


<class 'tensorflow.python.framework.ops.EagerTensor'>


[[0 0 0]
 [0 0 0]
 [0 0 0]]


<class 'tensorflow.python.framework.ops.EagerTensor'>


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


<class 'tensorflow.python.framework.ops.EagerTensor'>


[[-0.260936886 -0.413201362 0.770086646]
 [1.23721635 0.869195461 -1.01717019]
 [-0.0674135834 0.310766429 -0.048630055]]


<class 'tensorflow.python.framework.ops.EagerTensor'>


[[0.20362401 0.168828011 0.0176018476 0.314644814]
 [0.0510092974 0.417216182 0.138112068 0.271038055]
 [0.0897574425 0.534215 0.509768248 0.539209723]
 [0.309004784 0.707989335 0.426849961 0.609916925]]




#### 1.3. Math operations:

In [15]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1* n2
tf.print(n3)

2


In [17]:
n1 = tf.constant(4)
n2 = tf.constant(5)
n3 = tf.add(n1,n2)
tf.print(n3)

9


In [19]:
n1 = tf.constant(2)
n2 = tf.constant(3)
n3 = tf.multiply(n1,n2)
tf.print(n3)

6


In [21]:
n1 = tf.constant(2)
n2 = tf.constant(3)
n3 = tf.pow(n1,n2)
tf.print(n3)

8


#### 1.4. Matrix functions and operations: (describe briefly what makes each "new" function in each cell)

In [23]:
m1 = tf.constant([[1,2], [3,4]])
m2 = tf.constant([[1], [2]])
m3 = tf.matmul(m1, m2)                            # Matrix multiplication. Different from the element-wise multiplication with multiply().
print(m3)

tf.Tensor(
[[ 5]
 [11]], shape=(2, 1), dtype=int32)


In [25]:
m1 = tf.constant([[1,2], [3,4]])
m2 = tf.constant([[5, 6], [7, 8]])
m3 = tf.matmul(m1, m2)
print(m3)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [27]:
m3 = tf.multiply(m1, m2)
print(m3)

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [29]:
m3 = m1*m2
print(m3)

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [31]:
m3 = m1 + m2
print(m3)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [33]:
m3 = m1-m2
print(m3)

tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)


In [35]:
m3 = m1 / m2
print(m3)

tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [37]:
# Matrix functions.
m = tf.constant([[1.0,2.0],[3.0,4.0]])
m_diagonal = tf.linalg.diag([1,2,3])
m_transpose = tf.transpose(m)
m_inverse = tf.linalg.inv(m)
m_multiplied = tf.matmul(m, m_inverse)
m_determinant = tf.linalg.det(m)
my_matrices = [m, m_diagonal, m_transpose, m_inverse, m_multiplied, m_determinant]

for mat in my_matrices:
    res = mat
    print(np.round(res,3))
    print('\n')

[[1. 2.]
 [3. 4.]]


[[1 0 0]
 [0 2 0]
 [0 0 3]]


[[1. 3.]
 [2. 4.]]


[[-2.   1. ]
 [ 1.5 -0.5]]


[[ 1.  0.]
 [-0.  1.]]


-2.0




In the next cell:


1.   Create two rank 2 tensorflow variables initialised with random values. Booth matrices must have the same non-square shape (set the tensorflow ramdom seed to 100 to ensure reproducibility of the result).
2.   Multiply both matrices (in a matrix way -not element wise-) and save the result in a new variable.
3.   Concatenate and stack both matrices and save each result in a different new variable.
4.   Create one rank 2 tensorflow variable initialised with random values making sure that it is a square matrix. Obtain the determinant, the inverse and extract the diagonal of the matrix. Save each result in a new variable.
5.   Show the results using a print function. Transform all the results to numpy to avoid the "over-information" provided by the tensorflow variables. 





In [75]:
tf.random.set_seed(100)
np.random.seed(100)

In [77]:
matriz1 = tf.Variable(tf.random.normal([3, 2]))
matriz2 = tf.Variable(tf.random.normal([3, 2]))

In [79]:
print(matriz1)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.16052227, -1.6597689 ],
       [-1.232133  ,  0.5971658 ],
       [ 1.0609883 , -1.3277572 ]], dtype=float32)>


In [81]:
print(matriz2)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.64973587,  0.32791495],
       [-0.7519815 , -0.21430096],
       [ 0.52599317,  1.1992904 ]], dtype=float32)>


In [83]:
mult = tf.matmul(matriz1, tf.transpose(matriz2))
print(mult)

tf.Tensor(
[[-0.439966    0.23498031 -1.9061112 ]
 [-0.6047414   0.79856807  0.06808168]
 [ 0.2539707  -0.51330394 -1.0342939 ]], shape=(3, 3), dtype=float32)


In [85]:
concatVertical = tf.concat([matriz1, matriz2], axis=0)
print(concatVertical)

tf.Tensor(
[[ 0.16052227 -1.6597689 ]
 [-1.232133    0.5971658 ]
 [ 1.0609883  -1.3277572 ]
 [ 0.64973587  0.32791495]
 [-0.7519815  -0.21430096]
 [ 0.52599317  1.1992904 ]], shape=(6, 2), dtype=float32)


In [87]:
apilado = tf.stack([matriz1, matriz2], axis=0)
print(apilado.shape)
print(apilado)

(2, 3, 2)
tf.Tensor(
[[[ 0.16052227 -1.6597689 ]
  [-1.232133    0.5971658 ]
  [ 1.0609883  -1.3277572 ]]

 [[ 0.64973587  0.32791495]
  [-0.7519815  -0.21430096]
  [ 0.52599317  1.1992904 ]]], shape=(2, 3, 2), dtype=float32)


In [89]:
matriz_cuadrada = tf.Variable(tf.random.normal([3, 3]))
print(matriz_cuadrada)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 1.9533542 ,  0.7105855 , -1.4638338 ],
       [-2.4170957 ,  0.9670907 , -1.7943975 ],
       [-1.5562451 , -0.79322445,  1.7669842 ]], dtype=float32)>


In [91]:
det = tf.linalg.det(matriz_cuadrada)
print(det)

tf.Tensor(0.5671259, shape=(), dtype=float32)


In [93]:
inver = tf.linalg.inv(matriz_cuadrada)
print(inver)

tf.Tensor(
[[ 0.50336975 -0.16653214  0.24789421]
 [12.454893    2.0691383  12.419324  ]
 [ 6.034515    0.782195    6.359477  ]], shape=(3, 3), dtype=float32)


In [95]:
diag = tf.linalg.diag_part(matriz_cuadrada)
print(diag)

tf.Tensor([1.9533542 0.9670907 1.7669842], shape=(3,), dtype=float32)
