In [ ]:
# RED NEURONAL MODELO DE REGRESIÓN

In [69]:
import numpy as np
import tensorflow as tf 
import pandas as pd
import os
import warnings
import matplotlib.pyplot as pyplot
# Utilizaremos keras para crear la red neuronal
import keras
from keras.models import Sequential # Puede ser secuencial y 
from keras.layers import Dense
from sklearn .model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

warnings.filterwarnings('ignore')

In [71]:
# Creación de la ecuación

# Creamos valores aleatorios de una sola dimension
np.random.seed(0)
X1 = np.random.rand(100,1)
X2 = np.random.rand(100,1)

# la parte de np.random es ruido
y = 3*X1 + X2 + np.random.rand(100, 1)*0.1

X= tf.stack((X1,X2), axis=1)
print(X)

tf.Tensor(
[[[0.5488135 ]
  [0.67781654]]

 [[0.71518937]
  [0.27000797]]

 [[0.60276338]
  [0.73519402]]

 [[0.54488318]
  [0.96218855]]

 [[0.4236548 ]
  [0.24875314]]

 [[0.64589411]
  [0.57615733]]

 [[0.43758721]
  [0.59204193]]

 [[0.891773  ]
  [0.57225191]]

 [[0.96366276]
  [0.22308163]]

 [[0.38344152]
  [0.95274901]]

 [[0.79172504]
  [0.44712538]]

 [[0.52889492]
  [0.84640867]]

 [[0.56804456]
  [0.69947928]]

 [[0.92559664]
  [0.29743695]]

 [[0.07103606]
  [0.81379782]]

 [[0.0871293 ]
  [0.39650574]]

 [[0.0202184 ]
  [0.8811032 ]]

 [[0.83261985]
  [0.58127287]]

 [[0.77815675]
  [0.88173536]]

 [[0.87001215]
  [0.69253159]]

 [[0.97861834]
  [0.72525428]]

 [[0.79915856]
  [0.50132438]]

 [[0.46147936]
  [0.95608363]]

 [[0.78052918]
  [0.6439902 ]]

 [[0.11827443]
  [0.42385505]]

 [[0.63992102]
  [0.60639321]]

 [[0.14335329]
  [0.0191932 ]]

 [[0.94466892]
  [0.30157482]]

 [[0.52184832]
  [0.66017354]]

 [[0.41466194]
  [0.29007761]]

 [[0.26455561]
  [0.61801543]

In [73]:
model = Sequential()
model.add(Dense(1, input_shape=(2,))) # Definimos la capa de salida, tenemos 1 red neuronal, input_shape

# ya tenemos la red neuronal, ahora la vamos a compilar
model.compile(optimizer="sgd", loss="mse")

model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# ¿Porque 3 parametros? 2 parametros de entrada + 1 de bias o termino independiente

In [13]:
model.fit(X, y, epochs=50, batch_size=10)

Epoch 1/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 4.7044 
Epoch 2/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7734
Epoch 3/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.6479
Epoch 4/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.1419
Epoch 5/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.1287
Epoch 6/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7313 
Epoch 7/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7652
Epoch 8/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6148 
Epoch 9/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6692 
Epoch 10/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6316
Epoch 11/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5648
Epoch 12/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5889
Epoch 13/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6241
Epoch 14/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5238
Epoch 15/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4851
Epoch 16/50
10/

In [75]:
X_test = np.array([[0.2,0.1], [0.5,0.4], [0.8,0.3]]) # Nuevos datos para probar
predicciones = model.predict(X_test)
print(predicciones)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step
[[-0.05662826]
 [-0.31092507]
 [-0.1136101 ]]


In [ ]:
# RED NEURONAL REGRESIÓN LOGÍSTICA

In [77]:
np.random.seed(0)
X= np.random.rand(100,2)
y=np.random.randint(2, size=(100,1))

In [79]:
model = Sequential()
model.add(Dense(1, input_shape=(2,), activation='sigmoid'))

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [81]:
X_test = np.array([[0.2,0.1], [0.5,0.4], [0.8,0.3]]) # Nuevos datos para probar
predicciones = model.predict(X_test)
print(predicciones)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[[0.4737713 ]
 [0.44075072]
 [0.39261836]]


In [83]:
keras.__version__

'3.6.0'

In [ ]:
# PREDICCION DEL PRECIO DE LAS CASAS DE BOSTO

In [41]:
df= pd.read_csv("./data_boston.csv", header="infer", sep=";")
X= df.drop(columns=['price'])
y= df['price']

In [43]:
X.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio   black  lstat
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3  396.90   4.98
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8  396.90   9.14
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8  392.83   4.03
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7  394.63   2.94
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7  396.90   5.33

In [45]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: price, dtype: float64

In [ ]:
# a las redes neuronales les gustan los datos normalizados o escalados. para eso utilizaremos el minmaxScal. Pero solo escalaremos los valores de entrada

In [53]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)
# Tendremos 13 variables de entrada
n_vars = X_train.shape[-1]
n_vars

13

In [62]:
modelo = Sequential()
modelo.add(Dense(1, input_shape=(n_vars,), activation="linear"))

In [66]:
modelo.compile(optimizer="adam", loss="mae", metrics=["mse"])
modelo.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 1)                   │              14 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 14 (56.00 B)

 Trainable params: 14 (56.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
historico = modelo.fit(X_train, y_train, epochs = 2000, batch_size=10, validation_split=0.2) # podemos poner verbose=0 para que no salga la barra de progreso


Epoch 1/2000
29/29 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 22.1003 - mse: 566.9464 - val_loss: 22.0834 - val_mse: 556.2103
Epoch 2/2000
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.4588 - mse: 607.2072 - val_loss: 21.9138 - val_mse: 548.9415
Epoch 3/2000
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.1886 - mse: 597.6982 - val_loss: 21.7447 - val_mse: 541.7460
Epoch 4/2000
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.7386 - mse: 558.4028 - val_loss: 21.5771 - val_mse: 534.6714
Epoch 5/2000
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21.3085 - mse: 526.4029 - val_loss: 21.4090 - val_mse: 527.6329
Epoch 6/2000
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.0972 - mse: 587.5599 - val_loss: 21.2394 - val_mse: 520.6002
Epoch 7/2000
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.6999 - mse: 567.5862 - val_loss: 21.0700 - val_mse: 513.6297
Epoch 8/2000
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.1654 - mse: 529.2579 - val_loss: 20.9007 - val_mse: 506.7281
Epoch 9

In [ ]:
plt.plot(historico.history['mse'], c='b', label='Train')
plt.plot(historico.history['val_mse'], c='g', label='Validation')
plt.title('Training history')
plt.ylabel('MSE')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

In [ ]:
# Hacer predicciones y calcular el error
y_pred = modelo.predict(X_test)[:,0]  
RMSE = np.sqrt(np.mean((y_test-y_pred)**2))
np.round(RMSE, 3)
print(f'Error (RMSE): {RMSE:.4f}')

In [ ]:
MSE = modelo.evalueate(X_test, y_test)
print(MSE)
print(np.sqrt(MSE))