In [3]:
import numpy as np
from numpy import linalg as la
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [152]:
# Puntuaciones de los usuarios para peliculas:
pelis = pd.read_csv('./ratings_example.csv')
pelis = pd.pivot_table(pelis,index="userId", columns=["movieId"], values=["rating"], fill_value=0)
pelis.head(10)

rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10       
userId                                                                          
1          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    4.0   
3          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    4.0   
5          0.0    0.0    4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
6          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7          3.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    3.0   
8          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9          4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
10         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

         ...                                                                 \
movieId  ... 161084 161155 161594 161830 161918 161944 162376 162542 162672   
userId   ...                                                                  
1        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
6        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
8        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
10       ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

                
movieId 163949  
userId          
1          0.0  
2          0.0  
3          0.0  
4          0.0  
5          0.0  
6          0.0  
7          0.0  
8          0.0  
9          0.0  
10         0.0  

[10 rows x 9066 columns]

In [75]:
pelis_np = pelis.to_numpy()
print(pelis_np)
num_users, num_pelis = pelis_np.shape
print(f"Tenemos {num_users} usuarios que han visto {num_pelis} peliculas")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]]
Tenemos 671 usuarios que han visto 9066 peliculas


In [80]:
# Dame la similtud entre el usuario 1 y el usuario 2
pelis_user_1 = pelis_np[0]
pelis_user_2 = pelis_np[1]
S = cosine_similarity([pelis_user_1],[pelis_user_2])
# Si dos usuarios han puntuado películas completamente diferentes (es decir, no tienen películas en común), su similitud del coseno será 0.
S

array([[0.]])

In [82]:
# Dame la similtud entre el usuario 1 y 4
pelis_user_4 = pelis_np[3]
S = cosine_similarity([pelis_user_1],[pelis_user_4])
# Si ambos usuarios han puntuado películas similares de manera muy parecida, su similitud del coseno estaría cercana a 1
S

array([[0.07448245]])

In [121]:
pelis_np

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.]])

In [168]:
# Caculamos la matriz similtud para los usuarios (como los usuarios son dilas hay que transponer)
S = (pelis_np.T / la.norm(pelis_np.T, axis=0, keepdims=True)).T @ (pelis_np.T / la.norm(pelis_np.T, axis=0, keepdims=True))
print(S)

[[1.         0.         0.         ... 0.06291708 0.         0.01746565]
 [0.         1.         0.12429498 ... 0.02413984 0.17059464 0.1131753 ]
 [0.         0.12429498 1.         ... 0.08098382 0.13660585 0.17019275]
 ...
 [0.06291708 0.02413984 0.08098382 ... 1.         0.04260878 0.08520194]
 [0.         0.17059464 0.13660585 ... 0.04260878 1.         0.22867673]
 [0.01746565 0.1131753  0.17019275 ... 0.08520194 0.22867673 1.        ]]


In [178]:
# Celda 3: Calcular la matriz de recomendación
R = np.round(S @ pelis_np, 3)
R

array([[2.08760e+01, 8.46500e+00, 4.44900e+00, ..., 1.09000e-01,
        6.60000e-02, 2.88000e-01],
       [1.34802e+02, 8.36690e+01, 2.61450e+01, ..., 2.10000e-01,
        1.26000e-01, 4.87000e-01],
       [1.30619e+02, 5.19470e+01, 1.70170e+01, ..., 5.66000e-01,
        3.40000e-01, 4.20000e-01],
       ...,
       [6.39330e+01, 2.05860e+01, 1.13790e+01, ..., 1.04000e-01,
        6.20000e-02, 3.20000e-01],
       [1.44508e+02, 5.24800e+01, 2.31190e+01, ..., 1.78000e-01,
        1.07000e-01, 5.24000e-01],
       [2.00423e+02, 6.81640e+01, 2.54460e+01, ..., 5.40000e-01,
        3.24000e-01, 8.11000e-01]])

In [183]:

def get_top_recommendation(user_id):
    user_ratings = pelis_np[user_id]
    user_recommendations = R[user_id]
    
    # Excluir películas que el usuario ya ha visto
    mask = user_ratings == 0
    unseen_recommendations = user_recommendations * mask
    
    # Obtener el índice de la película con mayor puntuación
    top_movie_index = np.argmax(unseen_recommendations)
    
    # Obtener el ID de la película recomendada
    movie_id = pelis.columns[top_movie_index]
    
    return movie_id

# Generar recomendaciones para los primeros 9 usuarios
for user_id in range(9):
    recommended_movie = get_top_recommendation(user_id)
    print(f"Al usuario {user_id + 1} le recomendamos la película {recommended_movie}")

Al usuario 1 le recomendamos la película 260
Al usuario 2 le recomendamos la película 318
Al usuario 3 le recomendamos la película 260
Al usuario 4 le recomendamos la película 318
Al usuario 5 le recomendamos la película 318
Al usuario 6 le recomendamos la película 318
Al usuario 7 le recomendamos la película 296
Al usuario 8 le recomendamos la película 480
Al usuario 9 le recomendamos la película 296
