In [174]:
import numpy as np
from numpy import linalg as la
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [99]:
vuelos = pd.read_csv("./vuelos.csv")
vuelos

MAD-AGP  MAD-LPA  MAD-SVQ  MAD-VLC  MAD-IBZ  MAD-SCQ
0      0.0      0.0      1.0      0.0      0.0      2.0
1      0.0      2.0      1.0      1.0      0.0      0.0
2      0.0      0.0      1.0      1.0      1.0      1.0
3      0.0      0.0      1.0      2.0      0.0      0.0
4      0.0      0.0      1.0      1.0      0.0      0.0
5      0.0      0.0      2.0      0.0      0.0      1.0
6      1.0      0.0      0.0      1.0      0.0      1.0
7      0.0      1.0      0.0      1.0      0.0      2.0
8      1.0      2.0      0.0      0.0      0.0      1.0
9      1.0      0.0      1.0      0.0      1.0      0.0

In [5]:
vuelos_np = vuelos.to_numpy()
vuelos_np

array([[0., 0., 1., 0., 0., 2.],
       [0., 2., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 2., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 2., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 2.],
       [1., 2., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1., 0.]])

In [29]:
# Calculamos la norma Ecuclidia, esto nos dará la longitud de las búsquedas de cada usuario y nos hará que tengan una magnitud comparableable
norma = la.linalg.norm(vuelos_np, axis= 1, keepdims=True)
print(norma.size)
norma

10


array([[2.23606798],
       [2.44948974],
       [2.        ],
       [2.23606798],
       [1.41421356],
       [2.23606798],
       [1.73205081],
       [2.44948974],
       [2.44948974],
       [1.73205081]])

In [33]:
vuelos_normalizados = vuelos_np / norma
vuelos_normalizados

array([[0.        , 0.        , 0.4472136 , 0.        , 0.        ,
        0.89442719],
       [0.        , 0.81649658, 0.40824829, 0.40824829, 0.        ,
        0.        ],
       [0.        , 0.        , 0.5       , 0.5       , 0.5       ,
        0.5       ],
       [0.        , 0.        , 0.4472136 , 0.89442719, 0.        ,
        0.        ],
       [0.        , 0.        , 0.70710678, 0.70710678, 0.        ,
        0.        ],
       [0.        , 0.        , 0.89442719, 0.        , 0.        ,
        0.4472136 ],
       [0.57735027, 0.        , 0.        , 0.57735027, 0.        ,
        0.57735027],
       [0.        , 0.40824829, 0.        , 0.40824829, 0.        ,
        0.81649658],
       [0.40824829, 0.81649658, 0.        , 0.        , 0.        ,
        0.40824829],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        ]])

In [195]:
# Calcular la similtud para el v1 y v6

v1 = (vuelos_np.T)[0]
v6 = (vuelos_np.T)[5]

producto_escalar = v1 @ v6
norma_vuelo1 = la.norm(v1)
norma_vuelo6 = la.norm(v6)

S = producto_escalar / (norma_vuelo1 * norma_vuelo6)
# S = cosine_similarity([v1],[v6])
S

0.33333333333333337

In [203]:
# Calcular la matriz de similtud para todo los vuelos
S = (vuelos_np/ la.norm(vuelos_np, axis=0)).T @ (vuelos_np / la.norm(vuelos_np, axis=0))
print(S)

[[1.         0.38490018 0.18257419 0.19245009 0.40824829 0.33333333]
 [0.38490018 1.         0.21081851 0.33333333 0.         0.38490018]
 [0.18257419 0.21081851 1.         0.52704628 0.4472136  0.45643546]
 [0.19245009 0.33333333 0.52704628 1.         0.23570226 0.38490018]
 [0.40824829 0.         0.4472136  0.23570226 1.         0.20412415]
 [0.33333333 0.38490018 0.45643546 0.38490018 0.20412415 1.        ]]


In [217]:
# Calcular las recomendaciones para todos los usuarios
recomendaciones = np.round(vuelos_np @ S, 3)

print("Matriz de recomendaciones:")
print(recomendaciones)
print("\nMatriz original de búsquedas:")
print(vuelos_np)

Matriz de recomendaciones:
[[0.849 0.981 1.913 1.297 0.855 2.456]
 [1.145 2.544 1.949 2.194 0.683 1.611]
 [1.117 0.929 2.431 2.148 1.887 2.045]
 [0.567 0.877 2.054 2.527 0.919 1.226]
 [0.375 0.544 1.527 1.527 0.683 0.841]
 [0.698 0.807 2.456 1.439 1.099 1.913]
 [1.526 1.103 1.166 1.577 0.848 1.718]
 [1.244 2.103 1.651 2.103 0.644 2.77 ]
 [2.103 2.77  1.061 1.244 0.612 2.103]
 [1.591 0.596 1.63  0.955 1.855 0.994]]

Matriz original de búsquedas:
[[0. 0. 1. 0. 0. 2.]
 [0. 2. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 2. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 2. 0. 0. 1.]
 [1. 0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 2.]
 [1. 2. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0.]]


In [246]:
# ANOTACIONES DE LA FUNCIÓN: 
# Lo hacemos de forma descendente
# La función np.argsort() en NumPy devuelve los índices que ordenarían un array. 
def recomendar_vuelo(usuario_index):
    busquedas_usuario = vuelos_np[usuario_index] # Extraemos la fila de las veces que ha visitado ese usuario ese vuelo
    recomendaciones_usuario = recomendaciones[usuario_index] # Extrae la fila correspondiente al usuario de la matriz de recomendaciones. 
    
    # Encontrar el índice del vuelo más recomendado que aún no ha sido buscado
    for i in np.argsort(recomendaciones_usuario)[::-1]:
        if busquedas_usuario[i] == 0:
            return i
    
    return None  # Si todos los vuelos ya han sido buscados

# Recomendaciones para los usuarios especificados
usuarios = [0,1,2,3,4,5,6,7,8,9]  # Índices de los usuarios 1, 2, 3, 5, 7 y 10
for usuario in usuarios:
    vuelo_recomendado = recomendar_vuelo(usuario)
    print(f"Para el usuario {usuario + 1}, se recomienda el vuelo {vuelo_recomendado + 1 if vuelo_recomendado is not None else 'ninguno'}")

Para el usuario 1, se recomienda el vuelo 4
Para el usuario 2, se recomienda el vuelo 6
Para el usuario 3, se recomienda el vuelo 1
Para el usuario 4, se recomienda el vuelo 6
Para el usuario 5, se recomienda el vuelo 6
Para el usuario 6, se recomienda el vuelo 4
Para el usuario 7, se recomienda el vuelo 3
Para el usuario 8, se recomienda el vuelo 3
Para el usuario 9, se recomienda el vuelo 4
Para el usuario 10, se recomienda el vuelo 6
